### ISSUE TITLE
FR: Load spiffs on firmware update

### ISSUE THREAD

**Issue by doudar** [SmartSpin2K/SmartSpin2kFlasher#14]
As the title says, it would be nice to be able to select a spiffs.bin or have it automatically grab the one from OTAUpdates

**Comment by eMadman** [comment]
@MarkusSchneider - i've run into a user with limited internet access and seems to be running into issues connecting via hotspot on his phone.  Do you think this an achievable feature?  I'm looking into options for building/flashing it without setting up a platformio environment on the user's computer.

**Comment by eMadman** [comment]
assets for the manual uploader aren't available until it gets a wifi connection with internet access.

The user is going to take his to another location to get it onto wifi and configured initially.  Looks like flashing spiffs.bin using VS Code also didn't work for me, but I may be doing something wrong... or something is being set when it gets a wifi connection that isn't included with spiffs.bin.

**Comment by doudar** [comment]
fixed
